---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
