{
 "title": "vCluster dashboard - Infrastructure Overview",
 "description": "vCluster上のリソースとHostクラスタのリソースの監視を行います",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage % | Kubernetes Namespaces",
   "type": "timeseries",
   "description": "namespace ごとの CPU 使用率",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\nsum by (namespace) (\n  irate(container_cpu_usage_seconds_total{image!=\"\", pod!=\"\"}[5m])\n)\n/\nscalar(sum(kube_node_status_capacity{resource=\"cpu\"}))\n* 100\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage % | vCluster",
   "type": "timeseries",
   "description": "vcluster-otel-demo, vcluster-system namespace に配置された Pod ごとの CPU 使用率",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_cpu_usage_seconds_total{pod!=\"\", namespace=~\"^vcluster-.*\"}[5m])\n) \n/ \nscalar(sum(kube_node_status_capacity{resource=\"cpu\"})) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Thresholds:\n70%: Yellow\n90%: Red",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum by (namespace) (\n  irate(container_cpu_usage_seconds_total{pod!=\"\", namespace!=\"\"}[5m])\n) \n/ \nscalar(sum(kube_node_status_capacity{resource=\"cpu\"})) \n* 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "Thresholds:\n70%: Yellow\n90%: Red",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum by (namespace) (\n  container_memory_working_set_bytes{pod!=\"\", namespace!=\"\"}\n) \n/ \nscalar(sum(kube_node_status_capacity{resource=\"memory\"})) \n* 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage % | Kubernetes Namespaces",
   "type": "timeseries",
   "description": "namespace ごとのメモリ使用率",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\nsum by (namespace) (\n  container_memory_working_set_bytes{image!=\"\", pod!=\"\"}\n) \n/ \nsum by (namespace) (\n  kube_pod_container_resource_requests{resource=\"memory\"}\n)\n* 100\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage % | vCluster",
   "type": "timeseries",
   "description": "vcluster-otel-demo, vcluster-system namespace に配置された Pod ごとの memory 使用率",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{pod!=\"\", namespace=~\"^vcluster-.*\"}\n) \n/ \nscalar(sum(kube_node_status_capacity{resource=\"memory\"})) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "gauge",
   "description": "Thresholds:\n87.5 MiB/s: Yellow\n112.5 MiB/s: Red",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(container_fs_reads_bytes_total{pod!=\"\", namespace!=\"\"}[1m]) \n  + \n  rate(container_fs_writes_bytes_total{pod!=\"\", namespace!=\"\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (bytes/sec) Utilization",
   "type": "gauge",
   "description": "Thresholds:\n50.0 MB/s: Yellow\n100.0 MB/s: Red",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  irate(container_network_receive_bytes_total{namespace!=\"\"}[5m])\n  +\n  irate(container_network_transmit_bytes_total{namespace!=\"\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receiver Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Send Failed Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_log_records_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}