controlPlane:
  distro:
    k3s:
      enabled: true
      extraArgs:
        - "--flannel-backend=none"    # Cilium を入れるために無効化
        - "--disable-network-policy"  # Cilium Network Policy を使うため無効化

policies:
  networkPolicy:
    enabled: false # vCluster 自体の NetworkPolicy 制御を無効化