repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

---

environments:
  dev:
    kubeContext: ${DEV_KUBE_CONTEXT}-demo-eks-vcluster

---

releases:
  - name: otel-demo
    namespace: otel-demo
    chart: open-telemetry/opentelemetry-demo
    version: "0.40.1"
    createNamespace: true
    values: # ホスト側を使用するためデフォルトの監視コンポーネントは無効化
      - jaeger:
          enabled: false
        prometheus:
          enabled: false
        grafana:
          enabled: false
        opensearch:
          enabled: false

      - opentelemetry-collector:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: "500Mi"
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: "50Mi"
          config:
            connectors:
              spanmetrics: {}
            exporters:
              otlp:
                endpoint: "otelcol-to-alloy:4317"
                tls:
                  insecure: true
            service:
              pipelines:
                traces:
                  receivers: [otlp]
                  exporters: [otlp, spanmetrics]
                metrics:
                  receivers: [otlp, spanmetrics]
                  exporters: [otlp]
                logs:
                  receivers: [otlp]
                  exporters: [otlp]

      # 各種リソース
      - components:
          frontend:
            resources:
              limits:
                cpu: 2000m
                memory: 200Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 100m
                memory: 128Mi
                ephemeral-storage: "50Mi"

          cart:
            resources:
              limits:
                cpu: 2000m
                memory: 200Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 100m
                memory: 160Mi
                ephemeral-storage: "50Mi"

          checkout:
            resources:
              limits:
                cpu: 2000m
                memory: 256Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 50Mi
                ephemeral-storage: "50Mi"

          currency:
            resources:
              limits:
                cpu: 2000m
                memory: 50Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 20Mi
                ephemeral-storage: "50Mi"

          email:
            resources:
              limits:
                cpu: 2000m
                memory: 150Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 100m
                memory: 100Mi
                ephemeral-storage: "50Mi"

          accounting:
            resources:
              limits:
                cpu: 2000m
                memory: 300Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 200Mi
                ephemeral-storage: "50Mi"

          ad:
            resources:
              limits:
                cpu: 2000m
                memory: 350Mi
                ephemeral-storage: "1Gi"
              requests:
                cpu: 100m
                memory: 300Mi
                ephemeral-storage: "100Mi"

          fraud-detection:
            resources:
              limits:
                cpu: 2000m
                memory: 350Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 100m
                memory: 300Mi
                ephemeral-storage: "50Mi"

          kafka:
            enabled: true
            resources:
              limits:
                cpu: 2000m
                memory: 1Gi
                ephemeral-storage: "1Gi"
              requests:
                cpu: 100m
                memory: 500Mi
                ephemeral-storage: "100Mi"

          load-generator:
            resources:
              limits:
                cpu: 2000m
                memory: 1024Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 128Mi
                ephemeral-storage: "50Mi"

          frontend-proxy:
            resources:
              limits:
                cpu: 2000m
                memory: 128Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          product-catalog:
            env:
              - name: GOMEMLIMIT
                value: "64MiB"
              - name: PRODUCT_CATALOG_PORT
                value: "8080"
              - name: FLAGD_HOST
                value: "flagd"
              - name: FLAGD_PORT
                value: "8013"
              - name: DB_CONNECTION_STRING
                value: "postgres://otelu:otelp@postgresql/otel?sslmode=disable"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://$(OTEL_COLLECTOR_NAME):4317"
              - name: OTEL_SEMCONV_STABILITY_OPT_IN
                value: "database"
            resources:
              limits:
                cpu: 2000m
                memory: 512Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          product-reviews:
            resources:
              limits:
                cpu: 2000m
                memory: 256Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 128Mi
                ephemeral-storage: "50Mi"

          recommendation:
            resources:
              limits:
                cpu: 2000m
                memory: 256Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 128Mi
                ephemeral-storage: "50Mi"

          shipping:
            resources:
              limits:
                cpu: 2000m
                memory: 128Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          payment:
            resources:
              limits:
                cpu: 2000m
                memory: 128Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          quote:
            resources:
              limits:
                cpu: 2000m
                memory: 128Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          image-provider:
            resources:
              limits:
                cpu: 2000m
                memory: 128Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          flagd:
            resources:
              limits:
                cpu: 2000m
                memory: 128Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: "50Mi"

          valkey-cart:
            resources:
              limits:
                cpu: 500m
                memory: 64Mi
                ephemeral-storage: "500Mi"
              requests:
                cpu: 50m
                memory: 20Mi
                ephemeral-storage: "50Mi"

          postgresql:
            resources:
              limits:
                cpu: 2000m
                memory: 256Mi
                ephemeral-storage: "1Gi"
              requests:
                cpu: 50m
                memory: 128Mi
                ephemeral-storage: "100Mi"
