repositories:
  - name: loft
    url: https://charts.loft.sh

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

---

environments:
  dev:
    kubeContext: ${DEV_KUBE_CONTEXT}

---

releases:
  - name: vcluster
    namespace: vcluster-system
    chart: loft/vcluster
    version: "0.29.0"
    createNamespace: true
    timeout: 1800
    values:
    - sync:
        fromHost:
          ingressClasses:
            enabled: true
          storageClasses:
            enabled: true
        toHost:
          ingresses:
            enabled: true
          services:
            enabled: true
      controlPlane:
        statefulSet:
          persistence:
            volumeClaim:
              enabled: true
              size: 10Gi
              storageClass: gp2

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "77.13.0"
    values:
    - persistentVolumes:
        enabled: true
      persistentVolumeClaims:
        enabled: true
      prometheusSpec:
        scrapeInterval: "15s"
        evaluationInterval: "15s"
      additionalScrapeConfigs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: kube-etcd
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file:   /etc/prometheus/secrets/etcd-client-cert/etcd-ca
          cert_file: /etc/prometheus/secrets/etcd-client-cert/etcd-client
          key_file:  /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - source_labels: [__address__]
          action: replace
          target_label: __address__
          regex: ([^:;]+):(\d+)
          replacement: ${1}:2379
        - source_labels: [__meta_kubernetes_node_name]
          action: keep
          regex: .*mst.*
        - source_labels: [__meta_kubernetes_node_name]
          action: replace
          target_label: node
          regex: (.*)
          replacement: ${1}
        metric_relabel_configs:
        - regex: (kubernetes_io_hostname|failure_domain_beta_kubernetes_io_region|beta_kubernetes_io_os|beta_kubernetes_io_arch|beta_kubernetes_io_instance_type|failure_domain_beta_kubernetes_io_zone)
          action: labeldrop
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # 1. prometheus.io/scrape: "true" のアノテーションが付いているPodのみを監視対象として残す (keep)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
            
          # 2. prometheus.io/path のアノテーションから、メトリクスのパスを取得する
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            
          # 3. PodのIPアドレスと、prometheus.io/port アノテーションのポート番号を組み合わせて監視用のアドレスを生成する
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
            
          # 4. PodのNamespaceをメトリクスの `namespace` ラベルとして追加する
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
            
          # 5. Podの `app` ラベルを `job` ラベルとして採用する
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            target_label: job
