controlPlane:
  distro:
    k3s:
      enabled: true
      image:
        tag: v1.31.4-k3s1

  service:
    enabled: true
    spec:
      type: ClusterIP

  backingStore:
    etcd:
      deploy:
        enabled: false

  statefulSet:
    # vCluster コントロールプレーンの永続化
    persistence:
      volumeClaim:
        enabled: true
        size: 50Gi
        storageClass: gp3
    # リソース制限
    resources:
      limits:
        cpu: "8"
        memory: "8Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    pods:
      annotations: {
        "prometheus.io/scrape": "true",
        "prometheus.io/port": "8443",
        "prometheus.io/path": "/metrics"
      }

sync:
  # 仮想クラスタからホストへのリソース同期
  toHost:
    services:
      enabled: true

    ingresses:
      enabled: false

    persistentVolumeClaims:
      enabled: true

  # ホストから仮想クラスタへのリソース同期
  fromHost:
    nodes:
      enabled: true
      selector:
        all: true

    ingressClasses:
      enabled: false

    storageClasses:
      enabled: true

    # CSI ドライバー
    csiDrivers:
      enabled: true
    csiNodes:
      enabled: true
    csiStorageCapacities:
      enabled: true

# ネットワーク設定
networking:
  replicateServices:
    fromHost:
      - from: monitoring/alloy
        to: otel-demo/otelcol-to-alloy

# セキュリティとネットワークポリシー
policies:
  networkPolicy:
    enabled: false

  podSecurityStandard: baseline

  # vCluster 全体のリソース上限
  resourceQuota:
    enabled: true
    quota:
      requests.cpu: "4"
      requests.memory: "16Gi"
      limits.cpu: "96"
      limits.memory: "16Gi"
      count/pods: "50"
      count/services: "50"
      count/endpoints: "60"
      persistentvolumeclaims: "10"

  limitRange:
    enabled: true
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"

# メトリクス
integrations:
  metricsServer:
    enabled: false

# テレメトリ
telemetry:
  enabled: false
