controlPlane:
  distro:
    k3s:
      enabled: true
      extraArgs: # k3s標準のCNI(flannel)とNetworkPolicyを無効化し、Cilium用に空ける
        - "--flannel-backend=none"
        - "--disable-network-policy"

policies:
  networkPolicy:
    enabled: false # vCluster自体のNetworkPolicy制御も無効化